#!/usr/bin/env python3
"""Rotation-sweep analyzer — probes the 2D hidden-state rotation manifold.

Reads a rot_scan NPZ chunk (generated by scan_rotations.py) and runs a
battery of group-theoretic probes: Fourier spectrum, nematicity, language-mode
transitions, top-k rank decorrelation, and token-trajectory tracking.

The data captures the model's predictions as each token's final hidden state h
is rotated within the 2-plane spanned by {h, self-tangent t}. The probes
reveal the structure of this manifold: harmonic decomposition (m=2 nematic
dominance, m=1 rotary residual), antipodal language flips, and the effective
rank of the angular response.

This is NOT a RoPE/positional rotation sweep — no positional encoding is
touched. The rotation lives entirely in the residual-stream embedding space.

Usage: python analyze_rot_sweep.py [path/to/rot_scan_*.npz]
"""
import sys
import numpy as np
from collections import Counter

def load(fpath):
    d = np.load(fpath)
    return d["top"], d["logits"], d["angles"], d["tids"]

def probe_fourier(logits):
    """Harmonic decomposition of the top-1 logit response curve."""
    f = logits[:, :, 0]  # (scans, 360)
    f_dc = f.mean(axis=1, keepdims=True)
    F = np.fft.rfft(f - f_dc, axis=1)
    spec = np.abs(F[:, 1:])**2
    rel = spec.sum(axis=0) / spec.sum()
    print("=== FOURIER HARMONICS (top-1 logit) ===")
    freqs = np.fft.rfftfreq(360, d=1.0/360)
    order = np.argsort(rel)[::-1]
    for i in order[:8]:
        m = i + 1
        print(f"  m={m:2d}  period={360/m if m>0 else float('inf'):5.0f}deg  power={100*rel[i]:5.1f}%")
    m2p = 100 * rel[1] / (rel[0] + rel[1] + 1e-9)
    print(f"  m=2/(m=1+m=2) share: {m2p:.1f}% (nematic vs rotary)")
    return F, rel

def probe_token_trajectory(top, logits, angles, scan=0):
    """Track individual top-10 token logits as they fade in/out under rotation."""
    print("\n=== TOKEN TRAJECTORY (scan 0) ===")
    all_tokens = Counter()
    for a in range(360):
        all_tokens.update(top[scan, a].tolist())
    top_ids = [t for t, _ in all_tokens.most_common(10)]

    token_logits = {}
    for a in range(360):
        for k in range(8):
            tid = int(top[scan, a, k])
            token_logits.setdefault(tid, np.full(360, np.nan))[a] = logits[scan, a, k]

    print(f"  {'tid':>6} {'peak@':>6} {'range':>8}")
    for tid in top_ids:
        tr = token_logits[tid]
        valid = ~np.isnan(tr)
        if valid.sum() > 0:
            peak = np.nanargmax(tr)
            rng = tr[valid].max() - tr[valid].min()
            print(f"  {tid:6d} {int(angles[peak]):5d}deg  {rng:7.1f}")

def probe_nematicity(top, logits):
    """m=2/m=1 amplitude ratio by top-k depth."""
    print("\n=== TOP-K NEMATICITY (m2/m1 by rank) ===")
    for k in range(8):
        f = logits[:, :, k]
        F = np.fft.rfft(f - f.mean(axis=1, keepdims=True), axis=1)
        a1 = np.abs(F[:, 1]).mean()
        a2 = np.abs(F[:, 2]).mean()
        print(f"  top-{k+1}: m2/m1 = {a2/(a1+1e-9):.2f}")

def probe_decorrelation(top, logits):
    """Direction vs magnitude decorrelation with rotation angle."""
    print("\n=== DIRECTION vs MAGNITUDE DECORRELATION ===")
    top1 = top[:, :, 0]
    f = logits[:, :, 0]
    for lag in [1, 5, 20, 90, 180]:
        f_corr = np.corrcoef(f.ravel(), np.roll(f, lag, axis=1).ravel())[0, 1]
        same = (top1 == np.roll(top1, lag, axis=1)).mean()
        print(f"  lag={lag:3d}deg: mag_corr={f_corr:+.3f}  dir_same={same:.3f}")

def probe_language_map(top):
    """Script/character-class distribution by rotation angle."""
    print("\n=== SCRIPT MAP BY ANGLE QUADRANT ===")
    def script(s):
        if not s: return "empty"
        for c in s[:3]:
            n = ord(c)
            if 0x4E00 <= n <= 0x9FFF: return "CJK"
            elif 0x3040 <= n <= 0x30FF: return "kana"
            elif 0x0400 <= n <= 0x04FF: return "cyrillic"
            elif 65 <= n <= 90 or 97 <= n <= 122: return "latin"
            elif 48 <= n <= 57: return "digit"
            elif n <= 32: return "space"
            elif 33 <= n <= 47: return "punct"
        return "other"

    angle_script = [Counter() for _ in range(360)]
    for s in range(top.shape[0]):
        for a in range(360):
            # rough estimate: without tokenizer, classify by numeric range
            tid = int(top[s, a, 0])
            cls = "latin"  # heuristic: most low-range tokens are latin
            if tid >= 100000: cls = "CJK"
            elif tid >= 80000: cls = "symbol"
            elif tid <= 32: cls = "control"
            angle_script[a][cls] += 1

    for lo, hi in [(0, 90), (90, 180), (180, 270), (270, 360)]:
        merged = Counter()
        for a in range(lo, hi):
            merged.update(angle_script[a])
        total = sum(merged.values())
        top3 = merged.most_common(3)
        parts = ", ".join(f"{k}={100*v/total:.0f}%" for k, v in top3)
        print(f"  {lo:3d}-{hi:3d}deg: {parts}")

def probe_phase_coherence(top):
    """Are phase boundaries aligned across scans?"""
    flip_matrix = (top[:, 1:, 0] != top[:, :-1, 0]).astype(float)
    flat = flip_matrix.reshape(top.shape[0], -1)
    flat = flat - flat.mean(axis=1, keepdims=True)
    C = flat @ flat.T / (np.linalg.norm(flat, axis=1)[:, None] * np.linalg.norm(flat, axis=1)[None, :] + 1e-9)
    np.fill_diagonal(C, 0)
    print(f"\n=== CROSS-SCAN PHASE COHERENCE ===")
    print(f"  Mean off-diag flip-pattern correlation: {C.mean():+.3f}")

def probe_svd(logits):
    """Effective rank of the rotation response across tokens."""
    print("\n=== SVD EFFECTIVE RANK ===")
    M = logits.reshape(logits.shape[0], -1)
    U, S, Vt = np.linalg.svd(M - M.mean(axis=1, keepdims=True), full_matrices=False)
    rel = S**2 / (S**2).sum()
    for i in range(min(5, len(S))):
        print(f"  mode {i}: {rel[i]:.4f}")
    eff = (np.cumsum(rel) < 0.99).sum() + 1
    print(f"  effective rank (99%): {eff}")


if __name__ == "__main__":
    fpath = sys.argv[1] if len(sys.argv) > 1 else "151k_states/chunks/rot/rot_scan_0000000_0000064.npz"
    print(f"Loading {fpath}...")
    top, logits, angles, tids = load(fpath)
    n_scan, n_ang, kper = top.shape
    print(f"  {n_scan} scans x {n_ang} angles x top-{kper}\n")
    probe_fourier(logits)
    probe_token_trajectory(top, logits, angles)
    probe_nematicity(top, logits)
    probe_decorrelation(top, logits)
    probe_language_map(top)
    probe_phase_coherence(top)
    probe_svd(logits)